import Head from 'next/head'
import Image from 'next/image'
import styles from '@/styles/Home.module.css'
import Logo from '@/components/Logo'
import PhotoGrid from '@/components/Grid'
import { useState } from 'react'
import img1 from '@/public/1.jpg'
import img2 from '@/public/2.jpg'
import img3 from '@/public/3.jpg'
import img4 from '@/public/4.jpg'
import img5 from '@/public/5.jpg'
import img6 from '@/public/6.jpg'


export default function Home() {
  const images = [img1, img2, img3, img4, img5, img6];

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="">
      </div>
      <PhotoGrid images={images}/>
    </>
  )
}
